AWSTemplateFormatVersion: '2010-09-09'
Description: My first CloudFormation template
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
