name: CloudFormation Security Scan

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Conformity CLI
        run: pip install trend-micro-cloud-one-conformity-cli

      - name: Scan CloudFormation Template
        run: |
          conformity scan \
            --api-key ${{ secrets.CONFORMITY_API_KEY }} \
            --region ${{ secrets.CONFORMITY_REGION }} \
            --file template.yaml \
            --output result.json

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: result.json